<a href="https://colab.research.google.com/github/Ghan539/Gen_AI-Workshop/blob/main/Gen_AI_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Study_Hours": [1, 2, 2, 3, 3, 4, 4, 5, 5, 6],
    "Attendance":  [50, 55, 60, 65, 70, 72, 80, 85, 90, 95],
    "Result":      [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

print("=" * 60)
print("DATASET")
print("=" * 60)

print(df)

X = df[["Study_Hours", "Attendance"]].values
y = df["Result"].values

print("\nFeatures (X):")
print(X)

print("\nTarget (y):")
print(y)


X_mean = X.mean(axis=0)
X_std = X.std(axis=0)

X_scaled = (X - X_mean) / X_std

print("\nScaled Features:")
print(X)
print(X_scaled)



DATASET
   Study_Hours  Attendance  Result
0            1          50       0
1            2          55       0
2            2          60       0
3            3          65       0
4            3          70       0
5            4          72       1
6            4          80       1
7            5          85       1
8            5          90       1
9            6          95       1

Features (X):
[[ 1 50]
 [ 2 55]
 [ 2 60]
 [ 3 65]
 [ 3 70]
 [ 4 72]
 [ 4 80]
 [ 5 85]
 [ 5 90]
 [ 6 95]]

Target (y):
[0 0 0 0 0 1 1 1 1 1]

Scaled Features:
[[ 1 50]
 [ 2 55]
 [ 2 60]
 [ 3 65]
 [ 3 70]
 [ 4 72]
 [ 4 80]
 [ 5 85]
 [ 5 90]
 [ 6 95]]
[[-1.66666667 -1.54840181]
 [-1.         -1.19966266]
 [-1.         -0.85092352]
 [-0.33333333 -0.50218437]
 [-0.33333333 -0.15344522]
 [ 0.33333333 -0.01394957]
 [ 0.33333333  0.54403307]
 [ 1.          0.89277221]
 [ 1.          1.24151136]
 [ 1.66666667  1.59025051]]


In [ ]:
n_features = X_scaled.shape[1]
weights = np.zeros(n_features)
bias = 0.0
learning_rate = 0.1

epochs = 20

print("\nInitial Weights:", weights)
print("Initial Bias:", bias)

def step_function(value):
    if value >= 0:
        return 1
    else:
        return 0



Initial Weights: [0. 0.]
Initial Bias: 0.0


In [ ]:

print("=" * 60)
loss_history = []

for epoch in range(epochs):
    errors = 0
    for i in range(len(X_scaled)):
        weighted_sum = np.dot(X_scaled[i], weights) + bias
        prediction = step_function(weighted_sum)
        error = y[i] - prediction


        weights = weights + learning_rate * error * X_scaled[i]

        bias = bias + learning_rate * error

        # Count errors
        if error != 0:
            errors += 1

    loss_history.append(errors)

    print(
        f"Epoch {epoch + 1:2d} | "
        f"Errors: {errors:2d} | "
        f"Weights: {weights} | "
        f"Bias: {bias:.2f}"
    )

    if errors == 0:
       print("\nTraining converged!")
       break

print("\n" + "=" * 60)
print("FINAL MODEL PARAMETERS")
print("=" * 60)

print("Final Weights:", weights)
print("Final Bias:", bias)



Epoch  1 | Errors:  0 | Weights: [0.2        0.15344522] | Bias: 0.00

Training converged!

FINAL MODEL PARAMETERS
Final Weights: [0.2        0.15344522]
Final Bias: 0.0


In [ ]:
def predict(X):
  x_scale = (X-X_mean)/X_std
  predictions=[]

  for Sample in X_scaled:
    weighted_sum = np.dof(Sample , )

SyntaxError: expected ':' (430098129.py, line 1)

In [ ]:
_